TheAncientMerch/Web/TheAncientMerch.Web/Controllers/AccountsController.cs
namespace TheAncientMerch.Web.Controllers
{
    using System.Collections.Generic;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using TheAncientMerch.Services.Data.Accounts;
    using TheAncientMerch.Services.Data.Sculpture;
    using TheAncientMerch.Web.ViewModels.Account;

    [Authorize]
    public class AccountsController : Controller
    {
        private readonly IAccountService accountService;
        private readonly ISculptureService sculptureService;

        public AccountsController(
            IAccountService accountService,
            ISculptureService sculptureService)
        {
            this.accountService = accountService;
            this.sculptureService = sculptureService;
        }

        [HttpGet]
        public IActionResult MyAccount()
        {
            var userId = this.User.GetId();

            var viewModel = this.accountService.GetAccountViewModel(userId);
            return this.View(viewModel);
        }

        [HttpGet]
        public IActionResult PaymentsHistory(string route = "Bought")
        {
            route = route.ToLower();

            IEnumerable<PaymentViewModel> paymentsModel;

            var userId = this.User.GetId();

            if (route == "bought")
            {
                paymentsModel = this.accountService.GetUserBoughtSculpturesPayments(userId);
                return this.View(paymentsModel);
            }
            else if (route == "sold")
            {
                paymentsModel = this.accountService.GetUserSoldSculpturesPayments(userId);
                return this.View(paymentsModel);
            }

            return this.Redirect($"/Accounts/MyAccount");
        }

        [HttpGet]
        public IActionResult MySculptures()
        {
            var userId = this.User.GetId();
            var sculpturesView = this.sculptureService.GetAllUserSculptures(userId);
            return this.View(sculpturesView);
        }
    }
}

TheAncientMerch/Web/TheAncientMerch.Web/Controllers/DeitiesController.cs
namespace TheAncientMerch.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using TheAncientMerch.Services.Data.GreekDeity;

    [Authorize]
    public class DeitiesController : Controller
    {
        private readonly IGreekDeityService greekDeityService;

        public DeitiesController(IGreekDeityService greekDeityService)
        {
            this.greekDeityService = greekDeityService;
        }

        public IActionResult Gods()
        {
            var view = this.greekDeityService.GetAllGods();
            return this.View(view);
        }

        public IActionResult Titans()
        {
            var view = this.greekDeityService.GetAllTitans();
            return this.View(view);
        }

        public IActionResult Deity(int id)
        {
            var god = this.greekDeityService.GetDeity(id);

            return this.View(god);
        }
    }
}

TheAncientMerch/Web/TheAncientMerch.Web/Controllers/PostsController.cs
namespace TheAncientMerch.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using TheAncientMerch.Services.Data.Post;
    using TheAncientMerch.Web.ViewModels.Posts;

    [Authorize]
    public class PostsController : Controller
    {
        private readonly IPostService postService;

        public PostsController(IPostService postService)
        {
            this.postService = postService;
        }

        [HttpGet]
        public IActionResult Post(int id)
        {
            var viewModel = this.postService.GetPostById(id);

            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var viewModel = new CreatePostsInputViewModel
            {
                Categories = this.postService.GetForumCategories(),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePostsInputViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                model.Categories = this.postService.GetForumCategories();
                return this.View(model);
            }

            var userId = this.User.GetId();
            var postId = await this.postService.CreatePostAsync(model, userId);

            this.TempData["Message"] = "Post created successfully.";

            return this.RedirectToAction("Post", new { id = postId });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await this.postService.DeletePostAsync(id);
            this.TempData["Message"] = "Post deleted successfully.";
            return this.RedirectToAction("Categories", "Forums");
        }
    }
}

TheAncientMerch/Web/TheAncientMerch.Web/Controllers/SearchController.cs
namespace TheAncientMerch.Web.Controllers
{
    using System.Linq;

    using Microsoft.AspNetCore.Mvc;

    using TheAncientMerch.Services.Data.Search;
    using TheAncientMerch.Web.ViewModels.Articles;
    using TheAncientMerch.Web.ViewModels.Search;

    public class SearchController : Controller
    {
        private readonly ISearchService searchService;

        public SearchController(ISearchService searchService)
        {
            this.searchService = searchService;
        }

        [HttpGet]
        public IActionResult SearchArticle()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult SearchArticle(SearchArticleFormModel model)
        {
            var articles = this.searchService.SearchArticleByKeyword(model.Keyword);
            if (articles.Any())
            {
                model.Articles = articles;
                model.Keyword = string.Empty;
                return this.View("FoundArticle", model);
            }
            else
            {
                this.TempData["Message"] = "There was no article title found with the given keyword.";
                return this.View();
            }
        }

        [HttpGet]
        public IActionResult SearchSculpture()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult SearchSculpture(SearchSculptureFormModel model)
        {
            var sculptures = this.searchService.SearcSculptureByKeyword(model.Keyword);
            if (sculptures.Any())
            {
                model.Sculptures = sculptures;
                model.Keyword = string.Empty;
                return this.View("FoundSculpture", model);
            }
            else
            {
                this.TempData["Message"] = "There was no sculpture name found with the given keyword.";
                return this.View();
            }
        }

        [HttpGet]
        public IActionResult SearchDeity()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult SearchDeity(SearchGreekDeityFormModel model)
        {
            var deity = this.searchService.SearchGreekDeityByUsername(model.Name);
            if (deity != null)
            {
                model.Deity = deity;
                model.Name = string.Empty;
                return this.View("FoundDeity", model);
            }
            else
            {
                this.TempData["Message"] = "There was no deity name found with the given keyword.";
                return this.View();
            }
        }
    }
}

TheAncientMerch/Web/TheAncientMerch.Web/Views/Shared/_Layout.cshtml
@using TheAncientMerch.Common

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                  <img class="img-responsive" style="width: 200px"  src="~/images/logo/logo1.jpg" alt="logo">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-lg-inline-flex flex-lg-row-reverse">
                    <partial name="_LoginPartial" />
                    <div class="navbar-nav flex-grow-1">
                        <div class="dropdown">
                            <button class="btn btn" type="button" id="dropdownMenuButton"  data-toggle="dropdown">
                                Home
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </div>
                        </div>
                      @if (this.User.Identity.IsAuthenticated)
                        {
                            <div class="dropdown">
                                <button class="btn btn" type="button" id="dropdownMenuButton"  data-toggle="dropdown">
                                    Account
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item " asp-area="" asp-controller="Accounts" asp-action="MyAccount" asp-route-id="" >My Account</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Accounts" asp-action="PaymentsHistory">Payments history</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Accounts" asp-action="MySculptures">My Sculptures</a>
                                </div>
                            </div>
                            <div class="dropdown">
                                <button class="btn btn" type="button" id="dropdownMenuButton"  data-toggle="dropdown">
                                    Sculptures
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-area="" asp-controller="Sculptures" asp-action="All">All</a>
                                    <a class="dropdown-item " asp-area="" asp-controller="Search" asp-action="SearchSculpture">Search for Sculpture</a>
                                    <a class="dropdown-item " asp-area="" asp-controller="Sculptures" asp-action="Create">Create</a>
                                </div>
                            </div>
                            <div class="dropdown">
                                <button class="btn btn" type="button" id="dropdownMenuButton"  data-toggle="dropdown">
                                    Articles
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-area="" asp-controller="Articles" asp-action="All">All Articles</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Search" asp-action="SearchArticle">Search for Article</a>
                                    <a class="dropdown-item " asp-area="" asp-controller="Articles" asp-action="Categories" asp-route-id="" >Article Categories</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Articles" asp-action="Create">Create Article</a>
                                </div>
                            </div>
                            <div class="dropdown">
                                <button class="btn btn" type="button" id="dropdownMenuButton"  data-toggle="dropdown">
                                    Deities
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-area="" asp-controller="Deities" asp-action="Gods">Gods</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Deities" asp-action="Titans">Titans</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Search" asp-action="SearchDeity">Search for deity</a>
                                </div>
                            </div>
                            <div class="dropdown">
                                <button class="btn btn" type="button" id="dropdownMenuButton"  data-toggle="dropdown">
                                    Discussion
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item " asp-area="" asp-controller="Forums" asp-action="Categories" asp-route-id="" >Forum</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Forums" asp-action="Create">Create Category</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Posts" asp-action="Create">Create Post</a>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>

    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>