TheAncientMerch/Web/TheAncientMerch.Web/Controllers/SculpturesController.cs
namespace TheAncientMerch.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using TheAncientMerch.Services.Data.Sculpture;
    using TheAncientMerch.Services.Data.SculptureMaterial;
    using TheAncientMerch.Web.ViewModels.GreekDeitys;
    using TheAncientMerch.Web.ViewModels.Sculptures;

    [Authorize]
    public class SculpturesController : Controller
    {
        private readonly ISculptureMaterialService sculptureMaterialService;

        private readonly ISculptureService sculptureService;

        public SculpturesController(
            ISculptureMaterialService sculptureMaterialService,
            ISculptureService sculptureService
            )
        {
            this.sculptureMaterialService = sculptureMaterialService;
            this.sculptureService = sculptureService;
        }

        public IActionResult Create()
        {
            var viewModel = new CreateSculptureInputModel
            {
                Materials = this.sculptureMaterialService.GetAllMaterials(),
            };
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateSculptureInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var userId = this.User.GetId();

            await this.sculptureService.Create(model,userId);

            this.TempData["Message"] = "Sculpture created successfully.";

            return this.Redirect("/Sculptures/All");
        }

        public async Task<IActionResult> All([FromQuery] SculpturesQueryViewModel query)
        {
            var itemsPerPage = 6;
            var sculpturesQuery = await this.sculptureService.GetAllSculptures(query.PageNumber, itemsPerPage, query.Material, query.SculptureType, query.Color);

            return this.View(sculpturesQuery);
        }

        public IActionResult Sculpture(int id)
        {
            if (!this.sculptureService.ChekIfSculptureIdIsValid(id))
            {
                return this.BadRequest();
            }

            var sculpture = this.sculptureService.GetSculptureById(id);

            return this.View(sculpture);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (!this.sculptureService.ChekIfSculptureIdIsValid(id))
            {
                return this.BadRequest();
            }

            var currentUser = this.User.GetId();
            var viewModel = new EditSculptureViewModel();
            var model = this.sculptureService.GetSculptureById(id);

            if (currentUser != model.UserId)
            {
                return this.Redirect($"/Sculptures/Sculpture/{id}");
            }

            viewModel.Id = model.Id;
            viewModel.ImageUrl = model.ImageUrl;
            viewModel.Name = model.Name;
            viewModel.Description = model.Description;
            viewModel.Weigth = model.Weigth;
            viewModel.Height = model.Height;
            viewModel.Width = model.Width;
            viewModel.Materials = this.sculptureMaterialService.GetAllMaterials();
            viewModel.Origin = model.Origin;
            viewModel.Price = model.Price;
            viewModel.UserId = model.UserId;
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(int id, EditSculptureViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                model.Materials = this.sculptureMaterialService.GetAllMaterials();
                return this.View(model);
            }

            await this.sculptureService.EditSculptureAsync(model, id);

            this.TempData["Message"] = "Sculpture edited successfully.";

            return this.Redirect("/Sculptures/All");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await this.sculptureService.DeleteSculptureAsync(id);
            this.TempData["Message"] = "Sculpture deleted successfully.";
            return this.Redirect("/Sculptures/All");
        }

        [HttpGet]
        public IActionResult Buy(int id)
        {
            if (!this.sculptureService.ChekIfSculptureIdIsValid(id))
            {
                return this.BadRequest();
            }

            var userId = this.User.GetId();

            var viewModel = new BuySculptureFormModel
            {
                SculptureModel = this.sculptureService.GetSculptureForBuyViewModel(id, userId),
            };

            if (viewModel.SculptureModel == null)
            {
                this.TempData["Message"] = "Invalid sculpture.";
                return this.Redirect("/Sculptures/All");
            }

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Buy(BuySculptureFormModel model)
        {
            var userId = this.User.GetId();

            if (!this.ModelState.IsValid)
            {
                model.SculptureModel = this.sculptureService.GetSculptureForBuyViewModel(model.SculptureId, userId);
                return this.View(model);
            }

            await this.sculptureService.BuySculpture(model, userId);

            this.TempData["Message"] = "Thank you for your order! Delivery will be made within three working days!";

            return this.Redirect("/Sculptures/All");
        }
    }
}

TheAncientMerch/Web/TheAncientMerch.Web/Views/Sculptures/All.cshtml
@model SculpturesQueryViewModel

@{
    this.ViewData["Title"] = "All sculptures";
}

<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@this.ViewData["Title"]</strong></li>
    </ol>
</nav>



@if (this.TempData.ContainsKey("Message"))
{
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <strong>@this.TempData["Message"]</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<form>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label asp-for="SculptureType"></label>
            <select asp-for="SculptureType" class="form-control">
                <option value="@null">Search by type of sculpture</option>
               @foreach (int choice in Enum.GetValues(typeof(SculptureType)))
                {
                   <option value="@choice">@Enum.GetName(typeof(SculptureType), choice)</option>
                }
            </select>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Material"></label>
            <select asp-for="Material" class="form-control">
                <option value="">Search by material</option>
                @foreach (var material in Model.Materials)
                {
                    <option value="@material">@material</option>
                }
            </select>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Color"></label>
            <select asp-for="Color" class="form-control">
                <option value="@null">Search by color</option>
               @foreach (int choice in Enum.GetValues(typeof(SculptureColor)))
                {
                   <option value="@choice">@Enum.GetName(typeof(SculptureColor), choice)</option>
                }
            </select>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
</form>
<hr/>




<div class="row">
    
    @foreach (var sculpture in Model.Sculptures)
    {
        <div class="col-sm-6 col-md-4 mb-4">
            <div class="component">
                <div class="card card-height">
                    <div class="card-header">
                        <img class="card-img card-home-img" height="300" src="@sculpture.ImageUrl" alt="">
                    </div>
                    <div class="card-body">
                        <span class="badge badge-success mb-2">@sculpture.Material</span>
                        <span class="badge badge-warning mb-2">@sculpture.Color Color</span>
                        <span class="badge badge-light mb-2">Type: @sculpture.SculptureType</span>
                        <h4 class="card-title">@sculpture.Name</h4>
                        <p class="card-text">Price: <b>$@sculpture.Price USD</b></p>
                    </div>
                    <div class="card-footer">
                        <a asp-controller="Sculptures"
                           asp-action="Sculpture"
                           asp-route-id="@sculpture.Id"
                           class="btn btn-primary">
                            View More
                        </a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>


<partial name="_SculpturesPagingPartial" model="@Model" />

TheAncientMerch/Web/TheAncientMerch.Web/Views/Sculptures/Buy.cshtml
@model BuySculptureFormModel
@{
    ViewData["Title"] = "Checkout";
    var isFreeDelivery = Model.SculptureModel.Price >= 50;
    var totalPrice = Model.SculptureModel.Price + Model.VAT;
    if (!isFreeDelivery)
    {
        totalPrice += Model.DeliveryPrice;
    }
}

<div class="container">
    <div class="py-5 text-center">
        <h2>@ViewData["Title"]</h2>
        <p class="lead">Fill your data correctly and get @Model.SculptureModel.Name.</p>
    </div>

    <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Your cart</span>
            </h4>
            <ul class="list-group mb-3">
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">Product Price</h6>
                    </div>
                    <span class="text-muted">@Model.SculptureModel.Price</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">Delivery Price</h6>
                    </div>
                    <span class="text-muted">@(isFreeDelivery ? "Free" : Model.DeliveryPrice)</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">VAT</h6>
                    </div>
                    <span class="text-muted">@Model.VAT</span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                    <span>Total (USD)</span>
                    <strong>@totalPrice</strong>
                </li>
            </ul>
            @if (isFreeDelivery)
            {
                <h4 class=" text-danger">You have free delivery.</h4>
            }
        </div>

        <div class="col-md-8 order-md-1">
            <h4 class="mb-3">Billing address</h4>
            <form method="post">
                <input class="d-none" asp-for="SculptureId" value="@Model.SculptureModel.Id">

                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label asp-for="FirstName"></label>
                        <input asp-for="FirstName" class="form-control" placeholder="Example: Pesho">
                        <span class="text-danger" asp-validation-for="FirstName"></span>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label asp-for="LastName"></label>
                        <input asp-for="LastName" class="form-control" placeholder="Example: Petrov">
                        <span class="text-danger" asp-validation-for="LastName"></span>
                    </div>
                </div>

                <div class="mb-3">
                    <label asp-for="PhoneNumber"></label>
                    <input asp-for="PhoneNumber" class="form-control" placeholder="Example: +359 44 832 551">
                    <span class="text-danger" asp-validation-for="PhoneNumber"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" placeholder="Example: Test@gmail.com">
                    <span class="text-danger" asp-validation-for="Email"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Address"></label>
                    <input asp-for="Address" class="form-control" placeholder="1234 Main St">
                    <span class="text-danger" asp-validation-for="Address"></span>
                </div>

                <hr class="mb-4">
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="same-address">
                    <label class="custom-control-label" for="same-address">I am agree with terms and conditions.</label>
                </div>
                <hr class="mb-4">

                <h4 class="mb-3">Payment</h4>

                <div class="d-block my-3">
                    <div class="custom-control custom-radio">
                        <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked="" required="">
                        <label class="custom-control-label" for="credit">Credit card</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required="">
                        <label class="custom-control-label" for="debit">Debit card</label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required="">
                        <label class="custom-control-label" for="paypal">Paypal</label>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label asp-for="CardName"></label>
                        <input asp-for="CardName" class="form-control">
                        <span class="text-danger" asp-validation-for="CardName"></span>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label asp-for="CardNumber"></label>
                        <input asp-for="CardNumber" class="form-control">
                        <span class="text-danger" asp-validation-for="CardNumber"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3 mb-3">
                        <label asp-for="Expiration"></label>
                        <input asp-for="Expiration" class="form-control">
                        <span class="text-danger" asp-validation-for="Expiration"></span>
                    </div>
                </div>
                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">@ViewData["Title"]</button>
            </form>
        </div>
    </div>
</div>

TheAncientMerch/Web/TheAncientMerch.Web/Views/Sculptures/Create.cshtml
@model CreateSculptureInputModel


@{
    ViewData["Title"] = "Create Sculpture";
}





<div class="container">
    <div class="row">
        <div class="col-sm-12 offset-lg-2 col-lg-10 offset-xl-1 col-xl-10">
            <h1 class="text-center">@ViewData["Title"]</h1>
            <form method="post">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" placeholder="Sculpture Name">
                    <span asp-validation-for="Name" class="text-danger small"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageUrl"></label>
                    <input asp-for="ImageUrl" class="form-control" placeholder="Url">
                    <span asp-validation-for="ImageUrl" class="text-danger small"></span>
                </div>
                 <div class="form-group">
                    <label asp-for="Description"></label>
                    <input asp-for="Description" class="form-control" placeholder="Information about sculpture">
                    <span asp-validation-for="Description" class="text-danger small"></span>
                </div>
                
                 <div class="form-group">
                    <label asp-for="Origin"></label>
                    <input asp-for="Origin" class="form-control" placeholder="Info from where the sculpture is.">
                    <span asp-validation-for="Origin" class="text-danger small"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price"></label>
                    <input asp-for="Price" class="form-control" placeholder="Sculpture Price">
                    <span asp-validation-for="Price" class="text-danger small"></span>
                </div>
                 <div class="form-group">
                    <label asp-for="Height"></label>
                    <input asp-for="Height" class="form-control" placeholder="0">
                    <span asp-validation-for="Height" class="text-danger small"></span>
                </div>
                 <div class="form-group">
                    <label asp-for="Width"></label>
                    <input asp-for="Width" class="form-control" placeholder="0">
                    <span asp-validation-for="Width" class="text-danger small"></span>
                </div>
                 <div class="form-group">
                    <label asp-for="Weigth"></label>
                    <input asp-for="Weigth" class="form-control" placeholder="0">
                    <span asp-validation-for="Weigth" class="text-danger small"></span>
                </div>
                
                <div class="form-group">
                    <label asp-for="MaterialId"></label>
                    <select asp-for="MaterialId" class="form-control">
                     @foreach (var material in Model.Materials)
                     {
                        <option value="@material.Id">@material.Name</option>
                     }
                    </select>
                </div>
                <div class="form-group">
                   <label asp-for="SculptureType" ></label>
                     <select asp-for="SculptureType" class="form-control">
                        @foreach (int choice in Enum.GetValues(typeof(SculptureType)))
                          {
                              <option value="@choice">@Enum.GetName(typeof(SculptureType), choice)</option>
                          }
                 </select>
                </div>
                <div class="form-group">
                     <label asp-for="Color" ></label>
                      <select asp-for="Color" class="form-control">
                        @foreach (int choice in Enum.GetValues(typeof(SculptureColor)))
                        {
                            <option value="@choice">@Enum.GetName(typeof(SculptureColor), choice)</option>
                        }
                 </select>
                </div>
                <input type="submit" class="btn btn-info" value="@ViewData["Title"]" />
            </form>
        </div>
    </div>
</div>

TheAncientMerch/Web/TheAncientMerch.Web/Views/Sculptures/Sculpture.cshtml
@model SculptureViewModel

@{
    ViewData["Title"] = Model.Name;
    var userId = this.User.GetId();
}

<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Sculptures/All">All sculptures</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@this.ViewData["Title"]</strong></li>
    </ol>
</nav>

@if (this.TempData.ContainsKey("Message"))
{
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <strong>@this.TempData["Message"]</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}



<div class="container">
    <div class="row">
        <div class="col-md-9 mb40">
            <article>
                <img  src="@Model.ImageUrl" width="400"  height="400"  alt="" class="card rounded mx-auto d-block">
                <div class="post-content">
                    <hr/>
                    <h3 class="text-center">Description</h3>
                    <hr/>
                    <div class="container-md">@Model.Description</div>
                    
                    <hr class="mb40">
                    <h4 class="mb40 text-uppercase text-center font500">Origin</h4>
                      @Model.Origin
                    <hr class="mb40">
                </div>
            </article>

        </div>
        <div class="col-md-3 mb40">
            <div class="mb40">
                <h4 class="sidebar-title">Product information</h4>
                <ul class="list-unstyled categories">
                    <hr/>
                    <li class="item-description">
                      <strong>Name: </strong>@ViewData["Title"]
                    </li>
                    <hr/>
                     <li class="item-description">
                        <strong>Height: </strong>@Model.Height
                    </li>
                    <hr/>
                    <li class="item-description">
                        <strong>Width: </strong>@Model.Width
                    </li>
                    <hr/>
                    <li class="item-description">
                        <strong>Weigth: </strong>@Model.Weigth kg
                    </li>
                    <hr/>
                    <li class="item-description">
                        <strong>Price: </strong>$@Model.Price USD
                     </li>
                    <hr/>
                    <li>
                        
                        @if (userId == Model.UserId || User.IsInRole("Administrator"))
                        {
                            <div class="mb-1">
                              <div class="text-center pt-2">
                                <a  asp-controller="Sculptures" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary text-white">
                                    Edit
                                </a>
                              </div>
                              <div class="text-center pt-2">
                                    <form method="post" asp-controller="Sculptures" asp-action="Delete" asp-route-id="@Model.Id" id="deleteForm"></form>
                                     <button class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteModal">Delete</button>
                              </div>
                            </div>
                        }
                        else
                        {
                            <div class="text-center">
                            <a type="button" 
                                asp-controller="Sculptures"
                                asp-action="Buy"
                                asp-route-id="@Model.Id"
                             class="btn btn-primary tests text-uppercase text-center">
                                    Buy
                            </a>
                            </div>
                        }
                    </li>
                </ul>
            </div>
           
        </div>
    </div>
</div>


<div class="modal" tabindex="-1" role="dialog" id="deleteModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <p>Are you sure you want to remove "@Model.Name" Sculpture ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" onclick="deleteForm.submit()">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

TheAncientMerch/Web/TheAncientMerch.Web/Views/Sculptures/_SculpturesPagingPartial.cshtml
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text> }">
            <a class="page-link" asp-controller="Sculptures" asp-action="All" asp-route-PageNumber="@Model.FirstPageNumber"
            asp-route-SculptureType="@Model.SculptureType"
            asp-route-Material="@Model.Material"
            asp-route-Color="@Model.Color"><strong>First</strong></a>
        </li>
        <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text> }">
            <a class="page-link" asp-controller="Sculptures" asp-action="All" asp-route-PageNumber="@Model.PreviousPageNumber"
            asp-route-SculptureType="@Model.SculptureType"
            asp-route-Material="@Model.Material"
            asp-route-Color="@Model.Color"><strong>Previous</strong></a>
        </li>
        @for (int i = Model.PageNumber - 2; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-controller="Sculptures" asp-action="All" asp-route-PageNumber="@i"
                asp-route-SculptureType="@Model.SculptureType"
                asp-route-Material="@Model.Material"
                asp-route-Color="@Model.Color">@i</a></li>
            }

        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 2; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-controller="Sculptures" asp-action="All" asp-route-PageNumber="@i"
                asp-route-SculptureType="@Model.SculptureType"
                asp-route-Material="@Model.Material"
                asp-route-Color="@Model.Color">@i</a></li>
            }

        }
        <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text> }">
            <a class="page-link" asp-controller="Sculptures" asp-action="All" asp-route-PageNumber="@Model.NextPageNumber"
            asp-route-SculptureType="@Model.SculptureType"
            asp-route-Material="@Model.Material"
            asp-route-Color="@Model.Color"
           ><strong>Next</strong></a>
        </li>
        <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text> }">
            <a class="page-link" asp-controller="Sculptures" asp-action="All" asp-route-PageNumber="@Model.LastPageNumber"
            asp-route-SculptureType="@Model.SculptureType"
            asp-route-Material="@Model.Material"
            asp-route-Color="@Model.Color"><strong>Last</strong></a>
        </li>
    </ul>
</nav>